name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code.

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push Docker image.
        with:
          image: tebohoxthapeli/udagram-reverseproxy
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
